sudo: false
language: scala
scala:
  - 2.12.8
jdk:
  - oraclejdk8
env:
  global:
   - ENCRYPTION_ID: "9eb27d59440e"
cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot/"
script:
  - scripts/ci-build.sh
  - find $HOME/.sbt -name "*.lock" -delete
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
after_success:
  - scripts/api-doc.sh
  - scripts/publish.sh
  - scripts/coveralls.sh
notifications:
  email: false
